_format_version: "2.1"
_transform: true

consumers:
  - username: DASHBOARD
  - username: anon
    keyauth_credentials:
      - key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3Mzc1Njk2MCwiZXhwIjo0OTI5NDMwNTYwLCJyb2xlIjoiYW5vbiJ9.jDuQecR1RxD5iRzgW0rTcnnf45lkboJ6gyPzswnCERU
  - username: service_role
    keyauth_credentials:
      - key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3Mzc1Njk2MCwiZXhwIjo0OTI5NDMwNTYwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.4L3OvbLMK-h3RWnHXHLkHN31aoMhSuO4AGnGInf5Gmw

services:
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
  - name: rest
    url: http://rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
  - name: storage
    url: http://storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1
  - name: studio
    url: http://studio:3000
    routes:
      - name: studio-route
        paths:
          - /

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - authorization
        - apikey
        - content-type
        - x-client-info