_format_version: '2.1'
_transform: true

consumers:
  - username: DASHBOARD
  - username: anon
    keyauth_credentials:
      - key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3Mzc1Njk2MCwiZXhwIjo0OTI5NDMwNTYwLCJyb2xlIjoiYW5vbiJ9.jDuQecR1RxD5iRzgW0rTcnnf45lkboJ6gyPzswnCERU
  - username: service_role
    keyauth_credentials:
      - key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3Mzc1Njk2MCwiZXhwIjo0OTI5NDMwNTYwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.4L3OvbLMK-h3RWnHXHLkHN31aoMhSuO4AGnGInf5Gmw

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

basicauth_credentials:
  - consumer: DASHBOARD
    username: 'nhzWo1CMO9uZYKLl'
    password: 'z6DdvYdZmJxzOc4j5EeWYhzhIE6d3KCW'

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/verify
    plugins:
      - name: cors
  - name: auth-v1-open-callback
    url: http://auth:9999/callback
    routes:
      - name: auth-v1-open-callback
        strip_path: true
        paths:
          - /auth/v1/callback
    plugins:
      - name: cors
  - name: auth-v1
    url: http://auth:9999/
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
      - name: key-auth
      - name: request-transformer
        config:
          replace:
            headers:
              - "Authorization: return 'Bearer ' .. (kong.request.get_header('apikey') or '')"
      - name: acl
        config:
          allow: [admin, anon]

  - name: rest-v1
    url: http://rest:3000/
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
      - name: key-auth
      - name: request-transformer
        config:
          replace:
            headers:
              - "Authorization: return 'Bearer ' .. (kong.request.get_header('apikey') or '')"
      - name: acl
        config:
          allow: [admin, anon]

  - name: storage-v1
    url: http://storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors
      - name: request-transformer
        config:
          replace:
            headers:
              - "Authorization: return 'Bearer ' .. (kong.request.get_header('apikey') or '')"

  - name: dashboard
    url: http://studio:3000/
    routes:
      - name: dashboard-all
        strip_path: true
        paths:
          - /
    plugins:
      - name: cors
      - name: basic-auth
        config:
          hide_credentials: true